-- Database schema for 2FA implementation
--
-- WARNING: This file is GENERATED from the migration files in backend-2fa/migrations/.
-- Do NOT edit this file directly. Instead, add a new migration file and then
-- regenerate this file by running:
--
--   cat migrations/*.sql | grep -v '.down.sql' | ...  (see scripts/generate-schema.sh)
--
-- The migrations/ directory is the single source of truth for the database schema.


-- ---------------------------------------------------------------------------
-- NOTE: This section is auto-generated from the migration files.
-- Do not edit by hand. Run scripts/generate-schema.sh to regenerate.
-- ---------------------------------------------------------------------------

-- 001_create_schema_migrations.sql
-- Creates the schema_migrations tracking table that the migration runner
-- uses to track which migrations have been applied.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    applied_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checksum    TEXT NOT NULL
);

-- 002_create_base_tables.sql
-- Creates the base 2FA tables from the schema.

CREATE TABLE IF NOT EXISTS user_two_factor (
    user_id VARCHAR(255) PRIMARY KEY,
    secret TEXT NOT NULL,
    backup_codes TEXT NOT NULL,
    enabled BOOLEAN DEFAULT FALSE,
    algorithm VARCHAR(16) NOT NULL DEFAULT 'SHA1',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_two_factor_enabled ON user_two_factor(enabled);

CREATE TABLE IF NOT EXISTS recovery_code_usage (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    code_index INT NOT NULL,
    used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, code_index)
);

CREATE TABLE IF NOT EXISTS two_fa_audit_log (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    event VARCHAR(100) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    metadata TEXT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON two_fa_audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON two_fa_audit_log(timestamp DESC);

CREATE TABLE IF NOT EXISTS canary_accounts (
    user_id VARCHAR(255) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_two_factor
    ADD COLUMN IF NOT EXISTS algorithm VARCHAR(16) NOT NULL DEFAULT 'SHA1';

-- 002_create_ip_access_list.sql
-- Creates the ip_access_list table backing the admin IP allowlist/blocklist
-- endpoints (Issue #701). Entries are matched by CIDR containment in
-- application code; list_type distinguishes allow vs. block rules.

CREATE TABLE IF NOT EXISTS ip_access_list (
    id          BIGSERIAL PRIMARY KEY,
    cidr        TEXT NOT NULL,
    list_type   TEXT NOT NULL CHECK (list_type IN ('allow', 'block')),
    note        TEXT,
    created_by  TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ip_access_list_type ON ip_access_list(list_type);

-- 005_encrypt_existing_secrets.sql
-- Migration 005: Document encrypted secret storage requirement
--
-- MANUAL RE-ENCRYPTION REQUIRED FOR EXISTING RECORDS:
-- Existing plain-text secrets in `user_two_factor.secret` must be re-encrypted
-- before deploying application code that reads them as AES-256-GCM ciphertext.
--
-- Steps:
--   1. Set TOTP_ENCRYPTION_KEY in your secret store (64 hex chars = 32 bytes).
--   2. Run the provided migration script (scripts/encrypt_existing_secrets.py)
--      which reads each row, encrypts the secret with AES-256-GCM, and writes
--      back the ciphertext in the format `<nonce_hex>:<ciphertext_hex>`.
--   3. Only then deploy the new application binary.
--
-- There is intentionally no automatic SQL transformation here because the
-- encryption key is not available to the database engine.
--
-- This migration is a no-op at the SQL level; its purpose is to document
-- the required operational step in the migration history.
SELECT 1;

-- Table: two_fa_lockouts (not yet migration-tracked)
CREATE TABLE IF NOT EXISTS two_fa_lockouts (
    user_id VARCHAR(255) PRIMARY KEY,
    failed_attempts INT NOT NULL DEFAULT 0,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    locked_at TIMESTAMP NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
